[package]
name = "my_library"
version = "0.1.0"
authors = ["BuRny <gamingburny@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.13"
#pathfinding = "2.0"
indexmap = "1.3"
#pretty_assertions = "0.6.1"
fnv = "1.0.6"
